### ISSUE TITLE
A way play back Earthquake (Like JQuake)

### ISSUE THREAD

**Issue by Nikolas9999** [xspanger3770/GlobalQuake#107]
I think having a Play back is a good thing to add say you missed and Earthquake you can Play back it

**Comment by xspanger3770** [comment]
Agree. I was thinking of a similar functionality where at least the intensities would get stored for a replay in maybe another window with optional setting to store the entire waveform so that it can be analyzed later for improving the algorithms.

**Comment by xspanger3770** [comment]
A simple replay feature will be available in version 0.9.7 soon. It will only use the hypocenter location, p wave arrivals and maximum counts from each station that is assigned to that quake. It will be accessible by clicking on the quake in the list. 

A full-scale simulator with dataselect waveform download is planned sometime in the future.
