### ISSUE TITLE
feat: Cinema Mode easing and timing

### ISSUE THREAD

**Issue by HokoraYinphineMPP** [xspanger3770/GlobalQuake#138]
Add camera easing through [custom 4 point cubic beziers](https://cubic-bezier.com/#.17,.67,.79,.25) or some [common presets](https://easings.net).
Also plays into animation time/speed.
[`0.9.7_pre5`](https://github.com/xspanger3770/GlobalQuake/releases/tag/v0.9.7_pre5) settings currently have only one setting to change delay after each animation plays. 
Add multiple sliders to change animation rate (possibly even another slider to change rates for during events).

**Comment by xspanger3770** [comment]
Cinema mode updated to more quickly zoom on new event in the moment they occur. Also it will prioritize showing more important events now. More updates to come later.
