### ISSUE TITLE
Closest shoreline distance lookup table

### ISSUE THREAD

**Issue by xspanger3770** [xspanger3770/GlobalQuake#152]
Create a lookup table that can be used to quickly determine the distance to closest shoreline point based on geologic coordinates. It would be used to provide more accurate intensity estimations for offshore earthquakes.

**Comment by pmia712** [comment]
Hi, could I contribute to this one if it's still available?

**Comment by xspanger3770** [comment]
Hi, sure, I would be super happy to get help with this feature.

**Comment by xspanger3770** [comment]
It's too late for me today, but you can fork the repo and have a brief look at the code. I will explain the details later what can be used to make the work much easier.
