### ISSUE TITLE
A Java Exception has occured when launching GlobalQuake

### ISSUE THREAD

**Issue by Parac0** [xspanger3770/GlobalQuake#179]
![image](https://github.com/xspanger3770/GlobalQuake/assets/153055514/52c40760-4137-41f0-a01a-83c285337e49)

**Comment by xspanger3770** [comment]
This usually happens when you have wrong Java version installed. You need Java 17 or Java 21 to run GlobalQuake.

**Comment by Parac0** [comment]
Thanks!
