### ISSUE TITLE
What should I do to solve this error?

### ISSUE THREAD

**Issue by Parac0** [xspanger3770/GlobalQuake#181]
![image](https://github.com/xspanger3770/GlobalQuake/assets/153055514/bfb2ef97-abb4-45c4-9388-6b28cb51acad)

**Comment by Parac0** [comment]
What should I put in the IP address and port?

**Comment by YacineBoussoufa** [comment]
IP: 
>! eew.yacineboussoufa.it.eu.org
Port: 38000

As said previously you need version 0.10.0_pre15
