### ISSUE TITLE
No server on the latest Pre Released Version: GlobalQuake v0.10.0_pre18

### ISSUE THREAD

**Issue by aehqheadquarters** [xspanger3770/GlobalQuake#187]
i know its been 8 hour since this is released but cannot connect to server with the ip address and port provided before opening globalquake prereleased version.
![Screenshot 2023-12-19 183554](https://github.com/xspanger3770/GlobalQuake/assets/154391474/6cdcecc2-f564-4fdb-973d-63e72ab8655d)

**Comment by xspanger3770** [comment]
Really hard to tell why is that happening, my only guess is that you have too many connections to the server, but I could be wrong

**Comment by aehqheadquarters** [comment]
yeah I tried resetting networks including router and modems, still refuse to connect to server, the last prerelease 15 server is still working but prerelease 18 server is not working or dead.
