### ISSUE TITLE
Unable to create main directory, failed to load sounds, and the system cannot find the path specified

### ISSUE THREAD

**Issue by ikkue** [xspanger3770/GlobalQuake#201]
Unable to create main directory
![image](https://github.com/xspanger3770/GlobalQuake/assets/11213135/258a986d-4b40-4a31-8d17-b97d3130800f)

Failed to load sounds
![image](https://github.com/xspanger3770/GlobalQuake/assets/11213135/f9d8fe6e-d604-443f-a091-fbc702f3995e)

The system cannot find the path specified
![image](https://github.com/xspanger3770/GlobalQuake/assets/11213135/e7f1072b-f83d-4ff9-ba18-a4ff553f8c35)
![image](https://github.com/xspanger3770/GlobalQuake/assets/11213135/d3dd65b0-30d8-497a-9b2d-1b96ca02f134)
![image](https://github.com/xspanger3770/GlobalQuake/assets/11213135/6f3a0846-1517-4f9f-9536-980cd236fe23)

**Comment by Fealmar1** [comment]
I'm experiencing the exact same issue

**Comment by YacineBoussoufa** [comment]
Could you provide more information about your OS and the location the .jar file is located?

**Comment by ikkue** [comment]
> Could you provide more information about your OS and the location the .jar file is located?

OS is Windows 11 and file location is in drive D in its own GlobalQuake folder.

**Comment by YacineBoussoufa** [comment]
GlobalQuake doesn't have the permission to generate it's own folders. You have to either move the folder to a location where it has write and read permissions such as the Desktop. Or you can run GlobalQuake as Administrator.

**Comment by ikkue** [comment]
I tried running the JAR file via the Command Prompt running as administrator, and it seemed to have worked. But once the program opens, no stations are loaded.

https://github.com/xspanger3770/GlobalQuake/assets/11213135/c3c28027-6534-45dd-b520-18ff912c49be

**Comment by YacineBoussoufa** [comment]
Did you select the stations? After launching the app, and everything loads in the bottom there are two buttons, Select Stations and Launch GlobalQuake. You have to first select the station you want, and then launch the app. 

If you have already selected the stations and no data appear, make sure that you time is Synced. In Windows->Settings->Date & time->Time->Sync

**Comment by ikkue** [comment]
I have redownloaded v0.11.0_pre-1 using the installer, and all my time settings are properly synced, but it still shows 0 Available Channels
![image](https://github.com/xspanger3770/GlobalQuake/assets/11213135/8885f5d4-f7b8-4d9e-a396-7b785fb86b04)

**Comment by YacineBoussoufa** [comment]
Have you tried using the .jar file?

**Comment by ikkue** [comment]
> Have you tried using the .jar file?

I have tried and I experienced the same issue at the top of this comment thread; unable to create main directory and failed to load sounds. The .exe file doesn't have this problem.

**Comment by xspanger3770** [comment]
duplicate: #191
