### ISSUE TITLE
home location incorrect (Manjaro Linux)

### ISSUE THREAD

**Issue by bigbossvenomsnake** [xspanger3770/GlobalQuake#205]
![quake](https://github.com/xspanger3770/GlobalQuake/assets/122922905/5537259d-1175-4e02-a4f2-29a00f6a09aa)

home location should be further up

**Comment by bigbossvenomsnake** [comment]
i was wrong

**Comment by YacineBoussoufa** [comment]
![PoFacepalmGIF](https://github.com/xspanger3770/GlobalQuake/assets/46266665/4cfb458f-8823-4524-9c5f-0d30bb772fd9)

**Comment by bigbossvenomsnake** [comment]
this was my reaction as well when i realized
