### ISSUE TITLE
Feature Request: Allow filtering of old quakes by detection quality score

### ISSUE THREAD

**Issue by dare-to-recurse** [xspanger3770/GlobalQuake#208]
I'm mostly only interested in viewing quakes that got a score of B or better,
especially when looking through what's been happening during the night.

**Comment by xspanger3770** [comment]
Will be added in 0.10.1:
![image](https://github.com/xspanger3770/GlobalQuake/assets/100421968/8ca9c64e-016f-4abe-96eb-e6543f7b4e7c)
