### ISSUE TITLE
How to Modify or Customize Map Boundaries?

### ISSUE THREAD

**Issue by azzbm** [xspanger3770/GlobalQuake#210]
Due to the censorship policies in mainland China, it is not possible to publish videos that omit the "Tibet" region. This restriction prevents the publication of content containing this software. How can I modify the map boundaries to comply with the censorship policies in mainland China?

**Comment by YacineBoussoufa** [comment]
I tried searching for the entry "Tibet" and haven't found anything could you provide more informations? Was the name displayed on top left as "Tibet, China" or only "Tibet"?

**Comment by jiangxinlin** [comment]
![image](https://github.com/xspanger3770/GlobalQuake/assets/73826717/a70c3625-9c69-49f4-a84d-c4ba1e44546b)
I am referring to the map of southern Tibet, which is currently under the effective control of India. However, China claims sovereignty over a portion of it (the area depicted in the attached image). I would like to modify the borders to include this region as part of China. Is it possible to achieve this by modifying certain files?

**Comment by YacineBoussoufa** [comment]
Currently there is no way to change the map, in the future we will change the base map, with one with better quality and we'll edit this part. If you have any official geojson file of China (we need just the link) we'll see what we can do.

**Comment by WilliamHarrisonGB** [comment]
Here you go! I made CCP compliant GlobalQuake,
You have to modify the (geo)json files on the polygons folder to edit the borders.
its a rough outline but should work, I also edited the regions so it shows up as China (with Taiwan included).
I might make a fork so that you can download it for future GlobalQuake versions.
https://file.io/CUubXz4XKgAO, download link, github limits file sizes at 25MB so i had to upload it elsewhere
![image](https://github.com/xspanger3770/GlobalQuake/assets/125414146/b8e848e2-5312-4439-a166-69c3a21cabf7)

**Comment by jiangxinlin** [comment]
> Here you go! I made CCP compliant GlobalQuake, You have to modify the (geo)json files on the polygons folder to edit the borders. its a rough outline but should work, I also edited the regions so it shows up as China (with Taiwan included). I might make a fork so that you can download it for future GlobalQuake versions. https://file.io/CUubXz4XKgAO, download link, github limits file sizes at 25MB so i had to upload it elsewhere ![image](https://private-user-images.githubusercontent.com/125414146/299106546-b8e848e2-5312-4439-a166-69c3a21cabf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNDY2NDMsIm5iZiI6MTcwNjA0NjM0MywicGF0aCI6Ii8xMjU0MTQxNDYvMjk5MTA2NTQ2LWI4ZTg0OGUyLTUzMTItNDQzOS1hMTY2LTY5YzNhMjFjYWJmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QyMTQ1NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDA4NTkzNWZmNWQzNWIxNDU3Y2Q2Zjk2ZDdkYTE4NzVmM2Y4NWM3MDgwOWY0NGFmNTE0MDgwZjQ0MWI2YjY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uQakjn5op5RX3rLqOy5dFECg_BDAxu_3iaXIxBTImqM)

Thank you very much for your response. I have a GeoJSON file that complies with the Chinese government standards. The link is https://[geo.datav.aliyun.com/areas_v3/bound/100000_full.json](https://geo.datav.aliyun.com/areas_v3/bound/100000_full.json). You can use this JSON to generate a map that meets the requirements of the Chinese government. It would be great if you could consider adding an option in the settings to allow users to change the map based on specific territorial requirements of different countries. If possible, could you compile a special version of the JAR file specifically for China using this JSON to address potential reviews?

**Comment by jiangxinlin** [comment]
If you don't have access to the json connection you can use this file[geo_cn.json](https://github.com/xspanger3770/GlobalQuake/files/14030012/geo_cn.json)

**Comment by jiangxinlin** [comment]
If you don't have access to the json link you can use this file
[geo_cn.json](https://github.com/xspanger3770/GlobalQuake/files/14030069/geo_cn.json)

**Comment by jiangxinlin** [comment]
> If you don't have access to the json link you can use this file [geo_cn.json](https://github.com/xspanger3770/GlobalQuake/files/14030069/geo_cn.json)

This file provides precision down to each province and direct-controlled municipality in China. Perhaps you could format this file into 'polygons_converted' to display a high-quality map of China. If you only need the GeoJSON for the borders of China, please let me know, and I can search for that specifically.

**Comment by Mikifrfr** [comment]
> > If you don't have access to the json link you can use this file [geo_cn.json](https://github.com/xspanger3770/GlobalQuake/files/14030069/geo_cn.json)
> 
> This file provides precision down to each province and direct-controlled municipality in China. Perhaps you could format this file into 'polygons_converted' to display a high-quality map of China. If you only need the GeoJSON for the borders of China, please let me know, and I can search for that specifically.

I have added your geo_cn.geojson to globalquake here https://pixeldrain.com/u/okE9owGy, includes the small chinese islands
