### ISSUE TITLE
IRIS DMC Update delay

### ISSUE THREAD

**Issue by kuper-dot** [xspanger3770/GlobalQuake#213]
All station info fetched through IRIS DMC updates only once every 2.5-4 minutes, and when it updates, it already comes with a 30-second delay.  I tried different networks, I have tried using a VPN and this issue persists on two machines with Windows and Linux. It's a shame since IRIS DMC has quite large coverage.

**Comment by YacineBoussoufa** [comment]
Have you tried adding two more times IRIS host in the Seedlink tab? This decides the data request three times.

**Comment by kuper-dot** [comment]
Hi, yes I did, unfortunatly still no difference. Here are a few screenshots from around the world
![Screenshot 2024-01-26 103218](https://github.com/xspanger3770/GlobalQuake/assets/85749894/f2186167-dace-4486-9bdd-e98556b0ec83)
![Screenshot 2024-01-26 103207](https://github.com/xspanger3770/GlobalQuake/assets/85749894/196147f7-9d01-467e-8001-db0606458535)
![Screenshot 2024-01-26 103148](https://github.com/xspanger3770/GlobalQuake/assets/85749894/28816535-2dd9-4b8c-a787-702e5342e7e6)
![Screenshot 2024-01-26 103143](https://github.com/xspanger3770/GlobalQuake/assets/85749894/f4a26123-6be4-41e1-9c5f-a3955e85f92e)

**Comment by YacineBoussoufa** [comment]
This is strange, what is your ip from? Are you selecting all the stations around the world?

**Comment by kuper-dot** [comment]
Hi, I have a British IP, but I tried using VPN to connect from around the world (including the US). When it comes to the stations I selected a 25km filter

**Comment by YacineBoussoufa** [comment]
Try, instead of running it locally, to connect to our server
host: eew.yacineboussoufa.it.eu.org
Port 38000

**Comment by kuper-dot** [comment]
Hi again. As far as I can see, the delay in some areas is lower than in my local session. But in some other areas, where IRIS is the only source (like Alaska) there is not much difference from my local instance. But in Kyrgyzstan, the delay is much lower. I think that this is due to a remote server having a Geofon AD network station there, which is not available for some reason on my local server. 

I'm fine with running off the remote server, but it would still be nice to figure out how to properly host it myself. Thanks

**Comment by YacineBoussoufa** [comment]
Yeah, our server has more seedlinks available therefore some networks are faster. IRIS is probably delaying some network as per request of the owners. For instance look at Chinese stations which have a pretty big delay.

**Comment by kuper-dot** [comment]
So basically I can't do anything about the delay and I should use the remote server for best experience. I guess that I will stick to a local server where default SeadLinks has decent coverage and small delay and use the remote server for global tracking.

Thanks, everyone for your help.
