### ISSUE TITLE
GlobalQuake 0.10.1 Fatal Error 

### ISSUE THREAD

**Issue by coachjr** [xspanger3770/GlobalQuake#223]
Hello, i am experiencing an error in globalquake version 0.10.1 where i cant open it, even though i have everything including java 21. It says this: globalquake.core.exception.FatalIOException: Unable to create main directory!
	at globalquake.main.Main.initMainDirectory(Main.java:69)
	at globalquake.main.Main.main(Main.java:26). Are you able to fix this? Heres a image of the error as well: 
![image_2024-01-31_120037563](https://github.com/xspanger3770/GlobalQuake/assets/158285953/22bc4884-25df-4d94-82da-f9fa2f51b77b)

**Comment by YacineBoussoufa** [comment]
You are running GlobalQuake in a folder where the software is unable to create folders. Move GlobalQuake.jar to a folder in Desktop or in one where it has permission to read and write. Or you could launch GlobalQuake as an Administrator.

**Comment by xspanger3770** [comment]
Duplicate for #201
