### ISSUE TITLE
Stations With No Data

### ISSUE THREAD

**Issue by LessThan3Chips** [xspanger3770/GlobalQuake#237]
I believe that the stations are not connected to globalquake, because this is happening.
![Screenshot 2024-02-10 170757](https://github.com/xspanger3770/GlobalQuake/assets/65959770/c882cf69-3317-4c09-9bab-033f9c75b287)

This has been happening for the past few hours and I do not know why.

**Comment by YacineBoussoufa** [comment]
We are currently investigating the issue

**Comment by LessThan3Chips** [comment]
thanks for responding

**Comment by LessThan3Chips** [comment]
closing.
