### ISSUE TITLE
SEEDLINK AND STATION NEED FINE TUNE

### ISSUE THREAD

**Issue by koreyexpress2** [xspanger3770/GlobalQuake#242]
![Screenshot 2024-02-16 180310](https://github.com/xspanger3770/GlobalQuake/assets/64602951/2ac0710f-241b-4722-a1aa-ea52f58b2c9b)

![Screenshot 2024-02-16 181908](https://github.com/xspanger3770/GlobalQuake/assets/64602951/6fb69e95-b0a8-457f-a2df-db0c35db3335)

i have tried to update the seedlink and station but kept up getting error and network error and i check my pc and internet they are fine but something is wrong need a fine tuning to the seedlink and station

**Comment by xspanger3770** [comment]
This can either happen if the internet connection is too slow, there is an outage on the seedlink providers side or something is blocking the connection. It has nothing to do with GlobalQuake itself.
