### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by YuZZRA12** [xspanger3770/GlobalQuake#247]
![Fatal Error 21 02 2024 0_16_46](https://github.com/xspanger3770/GlobalQuake/assets/160637527/79e53bcd-b1db-44f0-b8b6-2ff54905aca1)
![Fatal Error 21 02 2024 0_17_20](https://github.com/xspanger3770/GlobalQuake/assets/160637527/c3603555-5263-43a9-95f6-2609091c341b)
I have files from Globalquake in a rar folder, I run this rar folder using Java and I have these errors.What should be done?

**Comment by YacineBoussoufa** [comment]
Move GlobalQuake to a location where it has permissions to create folders, such as a folder on the Desktop

**Comment by xspanger3770** [comment]
Duplicate: #201

**Comment by YuZZRA12** [comment]
if I make the archive a folder and move it to the desktop, how will I open it if it can only be opened using java except for the folder?how do I open this folder?
