### ISSUE TITLE
  Java Application launch failed.

### ISSUE THREAD

**Issue by isayeter** [xspanger3770/GlobalQuake#260]
<img width="245" alt="Screenshot 2024-03-03 at 17 45 54" src="https://github.com/xspanger3770/GlobalQuake/assets/3602109/28f59f8c-959b-4ed0-8940-e7029e7b7609">

Hello, when I try to open the app, I got the error: 

Java Application launch failed.
Check Console for possible error messages related to "/Users/jesus/Desktop/aGlobalQuake_v0.10.1.jar".

I have checked the Java version, it is: 21.0.2

<img width="403" alt="Screenshot 2024-03-03 at 17 46 02" src="https://github.com/xspanger3770/GlobalQuake/assets/3602109/56b3ecde-275d-4640-8d1c-c6c48a894c52">

Can you please help? 

Thank you.

**Comment by gsn1511** [comment]
Why are you running "aGlobalquake" instead of "Globalquake"?

**Comment by isayeter** [comment]
just renamed it because after I saw the error message, nothing happened whenever I relaunch the app, so I have decided to change the name and retried.

**Comment by gsn1511** [comment]
Launch the app while console is open. Does it show any error messages? Maybe it has to do with environment variables. Your java seems up to date

**Comment by isayeter** [comment]
oh thank you, from command line it worked. :/ 
<img width="844" alt="Screenshot 2024-03-04 at 01 18 31" src="https://github.com/xspanger3770/GlobalQuake/assets/3602109/649615f2-774e-4a11-a0d3-776821bf5da5">
