### ISSUE TITLE
ETNA2 not showing up

### ISSUE THREAD

**Issue by stevebiturbo** [xspanger3770/GlobalQuake#262]
I added my ETNA2 which I have in my office. port 18000 is open, globalquake can "see" etna in station configuration page, but its not showing on a map.
Note, ETNA2 has GPS and has time.
Can I add just one instrument, or do we need to create a whole network?

**Comment by YacineBoussoufa** [comment]
You would need a FDSNWS-station to be able to "locate" the device. Currently the only way to load a fdsnws-station is via HTTP/S, so you would need to create a web-server.

**Comment by stevebiturbo** [comment]
Alright, good to know, thank you so much!
