### ISSUE TITLE
when i lunch Global Quake i keep geting this error java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by Dannylad9862** [xspanger3770/GlobalQuake#264]
![image](https://github.com/xspanger3770/GlobalQuake/assets/58111547/122bf4a2-458d-47aa-b87b-c20c51d707b2)

**Comment by Dannylad9862** [comment]
just to inform you my pc is running this 
![image](https://github.com/xspanger3770/GlobalQuake/assets/58111547/22d1ba2d-86aa-437b-9476-fce55b42c0f1)

**Comment by WalkTheEarth** [comment]
Download the GlobalQuake .jar file and run it using the parameters "-Xmx" and see if that fixes it.

**Comment by Dannylad9862** [comment]
tried to do that but it does not open

this is how im running 
<img width="525" alt="image" src="https://github.com/xspanger3770/GlobalQuake/assets/58111547/29e65035-c909-48cc-94c0-89192aa5a352">

**Comment by WalkTheEarth** [comment]
Check how to open GQ via jar file [here](https://github.com/xspanger3770/GlobalQuake/wiki/Downloads-And-Installation#running)
