### ISSUE TITLE
Seedlink server connection issue

### ISSUE THREAD

**Issue by azzbm** [xspanger3770/GlobalQuake#266]
I ran GlobalQuake Server v11.0-pre2 on my server, It seems good but when I connect to my server, all IRIS sites are grayed out(No Data). But in the server interface, everything looks fine. Like these pictures:
<img width="244" alt="c6ebe5ce87b12f6acb2e1bf346069601" src="https://github.com/xspanger3770/GlobalQuake/assets/161959869/7549caec-caec-44fc-b44f-4e4cdd0994ed">
![1a52ab2a9211c76127ab14c6d63adcfc](https://github.com/xspanger3770/GlobalQuake/assets/161959869/59d8f98a-e9c0-4e9f-837d-6a6b846f7456)
![image](https://github.com/xspanger3770/GlobalQuake/assets/161959869/ee0c2311-1494-4b92-a19f-4df7c76c0433)
![image](https://github.com/xspanger3770/GlobalQuake/assets/161959869/6272b0aa-7db5-4a22-8932-10f36fda6084)

I have tried all the server area on AWS, none of them can connects to IRIS seedlink server stably. What causes it?

**Comment by HaruKor** [comment]
IRIS allows only 1000 stations per connection, when loading the stations in the Seedlink tab, add two more IRIS entries with the same configuration but different names IRIS 2, IRIS 3
![F4XjsCY](https://github.com/xspanger3770/GlobalQuake/assets/95398048/63a1a2c7-3856-4f1a-8dce-5fa6f6e7eb88)
