### ISSUE TITLE
Playground mode have no stations / channels

### ISSUE THREAD

**Issue by FNORE** [xspanger3770/GlobalQuake#267]
I don't know if it's just me, but I can't see the channel.
How do I fix it?
![스크린샷 2024-03-08 180315](https://github.com/xspanger3770/GlobalQuake/assets/162687310/e41d670c-72c8-441e-87df-949d2b28284e)

**Comment by YacineBoussoufa** [comment]
In playground mode, you can easily create earthquake scenarios at any place on Earth.

- Press R, rotate the globe to the place you want to insert stations and press SPACE. A dialog will pop up where you can specify the number of stations to be inserted as well as the radius in which the stations will be randomly generated.
- Press E to create a simulated earthquake similarly as the stations. You can specify it's magnitude and depth.
- The earthquake will originate at the moment you press OK in the dialog. You will be able to see the simulated quake as white waves spreading from the epicenter
- Once enough stations pick the artificial waveform, GlobalQuake will try to locate the earthquake hypocenter the same way it does with real events and you will see all the relevant information displayed.
- You can toggle the artificial quake visibility by pressing F.
- Use LEFT or RIGHT arrow key to fast backward / forward the time.
