### ISSUE TITLE
Unavailable stations in Slovenia, Bosnia and also all AM Raspberryshake

### ISSUE THREAD

**Issue by BobRice1964** [xspanger3770/GlobalQuake#272]
Hello
Thanks for this beautiful software.
I already added italian station from "protezione civile"
But I can't see available stations in Slovenia and Bosnia (excepted SL CRES and MN BLY)
Instead, in the youtube streaming GlobalquakeItalia https://www.youtube.com/watch?v=VK04J6N9Oa4 I see active stations
in those countries.
I found SL CRES and others SL stations in service.iris.edu's database
(see https://service.iris.edu/irisws/fedcatalog/1/query?cha=?HZ&start=2008-09-01&end=2009-01-01)
I already have http://service.iris.edu/fdsnws/station/1/ in Globalquake station database manager
but those stations are unavailable (grey).

I also added in station database manager raspberryshake station from
https://stationview.raspberryshake.org/fdsnws/station/1/
But they are unavailable too.
Any suggestion?
Thanks

Bob

**Comment by SG133** [comment]
Hello,

Some seedlinks, FDSNWS and stations are unavailable, or protected (private).
Thus it's not a bug in GQ, which rely on these data to run.

So if a link is not available or become private, there is nothing that the dev can do.

Regards,
Sébastien

**Comment by BobRice1964** [comment]
Thanks for the reply. Now it's all clear. Thank you very much!

Regards
Roberto
