### ISSUE TITLE
No earthquakes archived

### ISSUE THREAD

**Issue by Gurcano** [xspanger3770/GlobalQuake#277]
Databases updated. I've selected all stations and sources and there are no earthquake on the app. 
It says "No earthquakes archived".
![SS](https://github.com/xspanger3770/GlobalQuake/assets/19249088/75220460-0f90-4552-9200-e3dcf0a3dbc4)

**Comment by gsn1511** [comment]
It looks like you did not select any station 😅. Maybe try relaunching the program.

**Comment by Gurcano** [comment]
> It looks like you did not select any station 😅. Maybe try relaunching the program.

You right. There are another selection exists. I could found it finally. But this is so difficult to use :)

**Comment by xspanger3770** [comment]
this kind of issues is the reason why local mode wont exist in the future ;)
