### ISSUE TITLE
v10.1 on Windows 10 shows no date-time and map not updating

### ISSUE THREAD

**Issue by WGWC** [xspanger3770/GlobalQuake#283]
New install of EQ 10.1 on Win10 w Java 17.  After all earthquake servers downloaded successfully started v10 and immediate noted that time and date is not showing even though computer is gps sync'd and map is not updating at all like youtube live stream. 
If any information is provided please be specific about all steps to follow.

**Comment by SG133** [comment]
Hello,
Have you tried v0.11.0_pre-1 ?
Are you using local mode or server ?

**Comment by WGWC** [comment]
> Hello, Have you tried v0.11.0_pre-1 ? Are you using local mode or server ?

LOCAL

**Comment by SG133** [comment]
If you use local mode, you must select stations after the first launch.
Is it ok when you use server mode ?
server.globalquake.net 
Port: 38000

**Comment by WGWC** [comment]
> If you use local mode, you must select stations after the first launch. Is it ok when you use server mode ? server.globalquake.net Port: 38000

Server Mode wants an IP Address.  It doesn't like globalquake.net

**Comment by SG133** [comment]
Please use this version of GQ :
https://github.com/xspanger3770/GlobalQuake/releases/download/v0.11.0_pre-1/GlobalQuake_v0.11.0_pre-1_Installer_Windows.exe

**Comment by WGWC** [comment]
> Please use this version of GQ : https://github.com/xspanger3770/GlobalQuake/releases/download/v0.11.0_pre-1/GlobalQuake_v0.11.0_pre-1_Installer_Windows.exe

OK, I'll give it a shot and reply shortly

**Comment by WGWC** [comment]
That works MUCH BETTER.
Takes a long time to pull in 5328 Stations.
If we only want to monitor North, Central and South America and Japan region, do we need to pull in all 5K stations?
FYI Current computer config is:
Processor: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz, 3000 Mhz, 8 Core(s), 8 Logical Processor(s)
Installed Physical Memory (RAM)	8.00 GB
Total Physical Memory	7.87 GB
Available Physical Memory	1.19 GB
Total Virtual Memory	9.12 GB
Available Virtual Memory	1.18 GB

**Comment by WGWC** [comment]
> > Please use this version of GQ : https://github.com/xspanger3770/GlobalQuake/releases/download/v0.11.0_pre-1/GlobalQuake_v0.11.0_pre-1_Installer_Windows.exe
> 
> OK, I'll give it a shot and reply shortly

see below

**Comment by SG133** [comment]
In local mode you can select the areas you want to monitor.
On server mode, it's global only

**Comment by WGWC** [comment]
> In local mode you can select the areas you want to monitor. On server mode, it's global only

Am running it in Local Mode and got to the 5K and it has Error msg that it has run out of memory to select less stations.
So referring to last msg posted if we only want those regions,. please advise which to pick.

**Comment by SG133** [comment]
Click on Select Stations -> Deselect ALL -> Select Region

**Comment by WGWC** [comment]
> Click on Select Stations -> Deselect ALL -> Select Region

OH now we get it.
Its done all thru the GUI map.  Very creative!

**Comment by WGWC** [comment]
> Click on Select Stations -> Deselect ALL -> Select Region

We have selected 3200 station from North, South and Central America only.
Who do we need to contact to stream this on our utube channel???

**Comment by SG133** [comment]
Come to the official Discord : https://discord.gg/TVfcjhUj

**Comment by WGWC** [comment]
> Come to the official Discord : https://discord.gg/TVfcjhUj

created an account and verified it but wont let us log in to it. keeps saying bad user or password

**Comment by SG133** [comment]
I'm sorry but I can't help you for the Discord log in part
