### ISSUE TITLE
Station Connection Failures

### ISSUE THREAD

**Issue by NukeJets** [xspanger3770/GlobalQuake#292]
There are four stations that show errors upon loading.  They are:

earthquakescanada.nrcan.gc.ca

sislink.geofisica.ufrn.br

rtserve.ida.ucsd.edu

cwbpub.cr.usgs.gov

Is this a common occurrence? Is there anything I can do on my end to resolve the issue?

Thanks.

**Comment by AyanamiJoss** [comment]
Hello!
I've been checking your error and it's **mainly not a GlobalQuake error**, but rather the state of the servers (which may be down or because they have changed their status from public to private).
There are currently 3 of the 4 servers that are working (from the small list of servers that you say are not working)
![Captura de pantalla 2024-05-11 194704](https://github.com/xspanger3770/GlobalQuake/assets/136953526/99fc560f-bdc7-4afd-a693-3c349273df6c)
![Captura de pantalla 2024-05-11 194436](https://github.com/xspanger3770/GlobalQuake/assets/136953526/62709a69-6acb-4c0f-8392-340234534250)
![Captura de pantalla 2024-05-11 194613](https://github.com/xspanger3770/GlobalQuake/assets/136953526/e43dd627-f644-42d2-84d5-9d9091fba542)
![Captura de pantalla 2024-05-11 194642](https://github.com/xspanger3770/GlobalQuake/assets/136953526/0881b59b-cadd-4717-b879-3d70c31306ab)

**Comment by AyanamiJoss** [comment]
I have checked the errors on GlobalQuake, the server with IP "sislink.geofisica.ufrn.br" is not working at the moment and the server with the IP of "cwbpub.cr.usgs.gov" (belonging to USGS) is showing an error strange (which previously said is not a matter of the GlobalQuake team), so they cannot do anything about it, we just have to wait for them to try to fix the error.

![Captura de pantalla 2024-05-11 195247](https://github.com/xspanger3770/GlobalQuake/assets/136953526/303a655c-3e48-4246-af38-467ead8ba23f)

**Comment by NukeJets** [comment]
Thanks for the reply. I’m new to GlobalQuake and didn’t know if the problem
was with the sender or receiver.

Thanks again.

*Donald Arsenault*

Cell - (757) 846-0638


This Email message is for the sole use of the intended recipient(s) and may
contain confidential and privileged information.  Any unauthorized review,
use, disclosure or distribution is prohibited.  If you are not the intended
recipient, please contact the sender by reply Email and destroy all copies
of the original message.

**Comment by WalkTheEarth** [comment]
> Hello! I've been checking your error and it's **mainly not a GlobalQuake error**, but rather the state of the servers (which may be down or because they have changed their status from public to private). There are currently 3 of the 4 servers that are working (from the small list of servers that you say are not working) ![Captura de pantalla 2024-05-11 194704](https://private-user-images.githubusercontent.com/136953526/329820664-99fc560f-bdc7-4afd-a693-3c349273df6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2Mjc5ODMsIm5iZiI6MTcxNjYyNzY4MywicGF0aCI6Ii8xMzY5NTM1MjYvMzI5ODIwNjY0LTk5ZmM1NjBmLWJkYzctNGFmZC1hNjkzLTNjMzQ5MjczZGY2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQwOTAxMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDVjNTBhMjk1OTI1ZGZmZjQ5NGYwMDIxNGNhNjE3MGVhMWEyMzYzNDg2ZDNlMTgyMTJkMTFhNzA0YWM1YTk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-Dw-mXNfGJZc75M9DEkHQi7gWyeft2yvc5GAvX-znjo) ![Captura de pantalla 2024-05-11 194436](https://private-user-images.githubusercontent.com/136953526/329820595-62709a69-6acb-4c0f-8392-340234534250.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2Mjc5ODMsIm5iZiI6MTcxNjYyNzY4MywicGF0aCI6Ii8xMzY5NTM1MjYvMzI5ODIwNTk1LTYyNzA5YTY5LTZhY2ItNGMwZi04MzkyLTM0MDIzNDUzNDI1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQwOTAxMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjUwOWE5ZmU5ODJkZjM2MzkxNTE0MTkxNDM2MzhhODEyZmNlNjAyZGFiMDdmMjNmNTgxZmJmMTBiZWM4ZmQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5JS5Pb-uJwf5zchWnr4lSnn2SQLZt-Jgz7FVBZxuDNI) ![Captura de pantalla 2024-05-11 194613](https://private-user-images.githubusercontent.com/136953526/329820638-e43dd627-f644-42d2-84d5-9d9091fba542.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2Mjc5ODMsIm5iZiI6MTcxNjYyNzY4MywicGF0aCI6Ii8xMzY5NTM1MjYvMzI5ODIwNjM4LWU0M2RkNjI3LWY2NDQtNDJkMi04NGQ1LTlkOTA5MWZiYTU0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQwOTAxMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTQyZmY3MmUzYTJmZDNhOTY4YTgyYTBjZTMwNjQ4NmQ3OGViNzJkYzkzMTBjN2UxOTIxNTNlNWM5MGFjMmI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aj2ZiXisVjSC42df3Q27-TAfU_Jh17HxF80BatQfUhQ) ![Captura de pantalla 2024-05-11 194642](https://private-user-images.githubusercontent.com/136953526/329820654-0881b59b-cadd-4717-b879-3d70c31306ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2Mjc5ODMsIm5iZiI6MTcxNjYyNzY4MywicGF0aCI6Ii8xMzY5NTM1MjYvMzI5ODIwNjU0LTA4ODFiNTliLWNhZGQtNDcxNy1iODc5LTNkNzBjMzEzMDZhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQwOTAxMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OWYwODI0NWVkODVjZmUwNDg2NTAwNzc4NjFlNWNhMTZlMDdmYmFmYmY0NTM1OWQwODMyYjdkOGFlMWRkZjkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XrP27O4HbwnuNCee62nryeguo1hd8oB3qYH2EJrPLg4)

how do you have seiscomp on windows????

**Comment by xspanger3770** [comment]
Unfortunately, GlobalQuake doesn't own or control any of the seedlink networks and we cannot do anything about it if they are unreachable (case 1) or corrupted (case 2)
