### ISSUE TITLE
(pseudo) Issue - Playground mode stations far too sensitive.

### ISSUE THREAD

**Issue by WalkTheEarth** [xspanger3770/GlobalQuake#294]
The stations are far too sensitive. I simulated a m3.4 with high depth. The stations turned dark red. Please, make it more like real stations where in a similar EQ it would turn yellow.

**Comment by YacineBoussoufa** [comment]
As said in the realease notes: "⚠️ Work is in progress to implement the (yet missing) functionality to select specific simulation time, change stations sensitivity and random delay. Stay tuned for the full release."
We are aware of the issue, and it's not fully implemented yet.

**Comment by WalkTheEarth** [comment]
Alright. I'll still keep this issue up for issue tracking.

**Comment by xspanger3770** [comment]
duplicate: #259
