### ISSUE TITLE
STATION ITALY

### ISSUE THREAD

**Issue by Franc3x** [xspanger3770/GlobalQuake#295]
why can't I see the stations in Italy,Am I configuring something wrong?

windows 10

**Comment by YacineBoussoufa** [comment]
We do not disclose or share private server addresses and will deny any requests for such, you can still follow the monitoring in the youtube live streaming

**Comment by Franc3x** [comment]
This wasn't what I meant, I was wondering if I had made a mistake in some configuration from the Windows application

**Comment by Franc3x** [comment]
> Non divulghiamo né condividiamo indirizzi di server privati ​​e negheremo qualsiasi richiesta in tal senso, puoi comunque seguire il monitoraggio nello streaming live di YouTube

This wasn't what I meant, I was wondering if I had made a mistake in some configuration from the Windows application

**Comment by YacineBoussoufa** [comment]
Then, no you didn't do any mistake, the stations you see when you run GlobalQuake are those that you can use, all the others you "don't see" are private and cannot be used.

**Comment by Franc3x** [comment]
> Allora no, non hai sbagliato niente, le stazioni che vedi quando esegui GlobalQuake sono quelle che puoi usare, tutte le altre che "non vedi" sono private e non possono essere usate.

ths,
