### ISSUE TITLE
this is not Yunnan,China, it's Lai Chau, Vietnam

### ISSUE THREAD

**Issue by minhducngonguyen** [xspanger3770/GlobalQuake#301]
![image](https://github.com/xspanger3770/GlobalQuake/assets/173888297/11e0344b-206c-4803-9e64-1e3f5d126b0b)

**Comment by PopSlime** [comment]
![20240629134407](https://github.com/xspanger3770/GlobalQuake/assets/61138090/fae5a946-4756-4b40-9b6c-d79d18c59978)

**Comment by xspanger3770** [comment]
duplicate I guess: #240
