### ISSUE TITLE
Implement smooth scrolling in GlobePanel

### ISSUE THREAD

**Issue by xspanger3770** [xspanger3770/GlobalQuake#35]

**Comment by sindhunaydu** [comment]
Hi, I would like to work on this issue.

**Comment by sindhunaydu** [comment]
Here's my PR for review - https://github.com/xspanger3770/GlobalQuake/pull/37. Your project is very cool! This is a great first issue, I had fun working on it, looking forward to your feedback. Thanks!

**Comment by sindhunaydu** [comment]
@xspanger3770 I included your suggestion and reduced the multiplying value from 0.15 to 0.05 for a smoother transition. But 0.15 also works great, let me know if you want me to switch back or if there are anymore suggestions - https://github.com/xspanger3770/GlobalQuake/pull/53/files.
