### ISSUE TITLE
Add more GeoPolygon regions to GlobePanel

### ISSUE THREAD

**Issue by xspanger3770** [xspanger3770/GlobalQuake#42]
It would be cool to add more country borders, like USA states, Japan prefectures etc...
It's pretty easy to do, just find some good public geoJson files, put them in resources/polygons/, load them and tweak the limits when are they visible

**Comment by YacineBoussoufa** [comment]
This might be useful: https://github.com/deldersveld/topojson

**Comment by xspanger3770** [comment]
I found some great repo for more polygons: https://github.com/mledoze/countries

**Comment by xspanger3770** [comment]
Added regions/countries/prefectures to USA, Alaska, New Zealand, Japan and Italy in 0.9.7. More will likely be added later.
