### ISSUE TITLE
Include Restricted FDSNWS stations and some advises for the FDSNWS url downlaod

### ISSUE THREAD

**Issue by YacineBoussoufa** [xspanger3770/GlobalQuake#51]
I've noticed that during the download of some station sources, the restricted stations are automaticly rejected.
I advise to allow the download of them removing the "includerestricted=false" statement from the generation because some services don't properly recognize the GET request and sometimes some restricted station have in fact a Seedlink server available.

In addition I would like to advise to create a control for the FDSN url generation, especially for the endafter parameter because as previously said, some fdsnws providers don't use it creating some issue with them:
![image](https://github.com/xspanger3770/GlobalQuake/assets/46266665/26fb5dbc-a325-483a-b9b0-321af4387eb9)

**Comment by xspanger3770** [comment]
I tried testing the download with `includerestricted` and `endafter` parameters removed, but it lead to different problems:
when removing the `endafter` parameters, a lot of stations will get downloaded that are no longer running - mostly some temporary stations from IRIS. Also, the amount of stations that needs to get downloaded can trigger HTTP 413 response:
`The result set of your request exceeds the configured maximum number of objects (250000). Refine your request parameters.`

Maybe I will include another column with optional parameters for each fdsnws source or idk what is the best solution

**Comment by xspanger3770** [comment]
Yeah thinking about something like that... if 413 is returned, then generate new requests but with some limitation..maybe split by longitude into 2,4,8... requests

**Comment by xspanger3770** [comment]
I hope that all of the fdsnws services support at least geographic constraints for this to work

**Comment by xspanger3770** [comment]
@YacineBoussoufa Can you please show me which fdsnws provider had the issue with parsing `endafter` parameter? Can't find any.

**Comment by YacineBoussoufa** [comment]
https://esm-db.eu/fdsnws/station/1/query?level=station&format=text&endafter=2023-08-17T00:00:00&includerestricted=false
(doesn't support both includerestricted and endafter)
https://service.geonet.org.nz/fdsnws/station/1/query?level=station&format=text&endafter=2023-08-17T00:00:00&includerestricted=false (doesn't support includerestricted)

**Comment by xspanger3770** [comment]
Thanks! Trying to resolve this issues now...

**Comment by YacineBoussoufa** [comment]
I've also noted that 
https://ayiti.unice.fr/ayiti-seismes/fdsnws/station/1
and
https://sismoazur.oca.eu/fdsnws/station/1
Work only when the last "/" is excluded from the url on Globalquake, while on the web and other fdsnws on the software the last / is necessary

**Comment by xspanger3770** [comment]
Oh... that's really weird, but fortunately you can exclude or include the "/" from the url within the edit dialog so it shouldn't be an issue i guess

**Comment by xspanger3770** [comment]
This is really a nightmare... just found out that some fdsnws providers can't even parse the `channel` filter

This is ok and will only download HHZ channels
`https://sismoazur.oca.eu/fdsnws/station/1/query?minlongitude=-180.0&maxlongitude=180.0&level=channel&endafter=2023-08-17T19:14:34&format=xml&channel=HHZ`

But this will return empty page: (other providers return HHZ and BHZ channels)
`https://sismoazur.oca.eu/fdsnws/station/1/query?minlongitude=-180.0&maxlongitude=180.0&level=channel&endafter=2023-08-17T19:14:34&format=xml&channel=HHZ,BHZ`

**Comment by YacineBoussoufa** [comment]
This can be fixed with using double parameters "&channel=HHZ&channel=BHZ" keep in mind that oca.eu doesn't have any HHZ station in their fdsnws

**Comment by xspanger3770** [comment]
Oh great! hope it's universal

**Comment by YacineBoussoufa** [comment]
Never mind, just tested again with oca and doesn't work... it only shows one channel... I think the easies way it to use "&channel=?HZ"

**Comment by xspanger3770** [comment]
Yeah I see only HHZ channels are returned...

**Comment by YacineBoussoufa** [comment]
As I said i think "&channel=?HZ" is the most appropriate, because some station also only use EHZ for example.

**Comment by xspanger3770** [comment]
?HZ seems like the solution

**Comment by xspanger3770** [comment]
Also I discovered that different fdsnws providers run different versions of the protocol... for example 
https://esm-db.eu/fdsnws/station/1/version
shows that esm runs on 0.0.1 and this version doesn't support the `endafter` parameter as you can see here:
https://esm-db.eu/fdsnws/station/1/application.wadl

**Comment by YacineBoussoufa** [comment]
Good job 😍

**Comment by xspanger3770** [comment]
Closed - those new cool features will be ready in 0.9.3.
