### ISSUE TITLE
No available stations (timezone issue)

### ISSUE THREAD

**Issue by magnanim0us** [xspanger3770/GlobalQuake#56]
Stations are all unavailable. When you start it (from command prompt), it says there are available stations but there is actually none. The stations were never available for me. Issue persists with both Windows and Ubuntu, on 0.9.0 and 0.9.1. 

![image](https://github.com/xspanger3770/GlobalQuake/assets/129902118/8da7cfc8-71b7-42ea-b80e-f69dc4e1e8fa)
![image](https://github.com/xspanger3770/GlobalQuake/assets/129902118/507d2cf4-709f-4067-b55c-c6eeec2bbddc)

**Comment by xspanger3770** [comment]
Oh, that's really weird, I've never had this issue before. Seems like the station sources downloaded correctly but there might be some issue with connection to the seedlink networks. Can you show what's displayed in the seedlink networks tab and perhaps select the seedlink networks and hit update button?

**Comment by xspanger3770** [comment]
Was thinking about what might have caused this issue, because the available stations got downloaded but somehow they didn't get included, and what I'm thinking about is a timezone issue, because when the stations get downloaded, they get filtered away when their delay is larger than 15 minutes, but if there is a timezone issue, it might actually filter all of them...

**Comment by magnanim0us** [comment]
> Oh, that's really weird, I've never had this issue before. Seems like the station sources downloaded correctly but there might be some issue with connection to the seedlink networks. Can you show what's displayed in the seedlink networks tab and perhaps select the seedlink networks and hit update button?

I've already tried updating them all but that didn't really change anything.
![image](https://github.com/xspanger3770/GlobalQuake/assets/129902118/c5347f1f-8186-4c5f-9b50-bc09955b8681)

**Comment by magnanim0us** [comment]
> Was thinking about what might have caused this issue, because the available stations got downloaded but somehow they didn't get included, and what I'm thinking about is a timezone issue, because when the stations get downloaded, they get filtered away when their delay is larger than 15 minutes, but if there is a timezone issue, it might actually filter all of them...

I've changed my timezone (to UTC) and it seems to work normally. As in the picture below it seems like only 4k of them are online; I'm assuming this has got to do with the fact that some stations do not have any seedlink.
![image](https://github.com/xspanger3770/GlobalQuake/assets/129902118/4139a7cf-747b-4453-8a45-e9be9fc2831c)

**Comment by YacineBoussoufa** [comment]
Switching to UTC broke everything for me, so UTC+2 is the solution I guess

**Comment by xspanger3770** [comment]
Yeah that confirms that there is a timezone issue... thanks for reporting this! Will probably release a hotfix tomorrow as it might affect a lot of users...

**Comment by xspanger3770** [comment]
The problem is in TimeFixer.java file:
`return TimeZone.getTimeZone("CET").getOffset(System.currentTimeMillis());`

A code that I wrote maybe 4 years ago when I never thought about releasing GlobalQuake...

**Comment by xspanger3770** [comment]
I added notices to readme and to the releases about this issue and will try to release a fix tomorrow when I'm back from a trip...
Also @magnanim0us the 4k available stations is about what you can expect in version 0.9.1 as many stations indeed don't have any seedlink

**Comment by xspanger3770** [comment]
Closed - hotfix in 0.9.2 by removing the delay check and correct handling will be added in 0.9.3.
