### ISSUE TITLE
Improve installation tutorial

### ISSUE THREAD

**Issue by xspanger3770** [xspanger3770/GlobalQuake#95]
It would be awesome to improve the installation tutorial in README so that it explains how to install Java on various platforms as well as GlobalQuake itself.

**Comment by gsn1511** [comment]
We could make a Youtube video too

**Comment by xspanger3770** [comment]
Sure why not :))

**Comment by CentreMetre** [comment]
I can expand on the java installation, would images be acceptable, or should it only be text to avoid to much 'clutter' (for lack of a better term)? I was also thinking of maybe splitting the java and GlobalQuake download and install into 2 separate 'subsections' under the downloads sections for example and pictures of deemed appropriate:

## Download and Installation
### Java

1. lorem
2. ipsum
3. etc

### GlobalQuake

1. lorem
2. ipsum
3. etc

**Comment by xspanger3770** [comment]
I've also an idea to create a new folder `tutorials` and create separate README.MD file there, so that it wont clutter the main README and many images can be added. In the main README would simply be a link to this tutorial.

**Comment by CentreMetre** [comment]
Thats actually a good idea, you could expand on the tutorial more without it just filling out the README. Also do you mean file instead of folder? Or do you mean folder with 2 files for Java and GlobalQuake separately?

**Comment by xspanger3770** [comment]
I meant a new **folder** called `tutorials` and inside that folder would be a new `README.MD` file containing all the tutorials, maybe with more sections for Java and GlobalQuake

**Comment by xspanger3770** [comment]
... That way if someone opens the `tutorials` folder, they would see it right away

**Comment by CentreMetre** [comment]
Ah ok, i was thinking of maybe just having a file called "Installation Tutorial" or something along those lines, to me it seems a bit pointless having a folder with just one file but im down with whatever

**Comment by CentreMetre** [comment]
ah so for if theres future tutorials added for other things?

**Comment by xspanger3770** [comment]
Yes, that was kinda my idea, there might be more tutorials added in the future and maybe it's just me, but I don't want the root directory full of files. The thing is that if you create a file called `README.md`, GitHub will automatically show the contents if user enters the directory

**Comment by CentreMetre** [comment]
Yea i totally agree, i didnt think about future tutorials being added, i agree it would definitely be best to had a new directory for them. Ah didnt know about github showing the REAME.md, i assume it would show under the main readme in the root directory? Also i guess only the installation tutorials would be README.md so they show up, and other would just have self explanatory names?

**Comment by xspanger3770** [comment]
Yes, that's how I was thinking it would be good to do. In the `tutorials` directory would be that one `README.md` containing just the installation, because that's what newcomers will probably want to know first, and the other files would have their corresponding names and they would be linked from the root's README

**Comment by CentreMetre** [comment]
Sounds good, what about images for in the tutorials? Should they be a thing or just text?

**Comment by xspanger3770** [comment]
I mean, that probably depends on you, how much effort do you want to put into it, but images would surely make the tutorial easier to understand. You can always start with a text version and add images later.

**Comment by CentreMetre** [comment]
True, i willing to add images to aide my explanation, i know i prefer images when following a tutorial.

Should the tutorial point to using the latest version of java, or java 17 (which i think is what this app uses), especially since 20 is short term support aswell?

**Comment by xspanger3770** [comment]
I would make the tutorial to recommend Java 17 for the reasons you've said, and also there were some issues for people trying Java 21. 
You can definitely upload the images here, you can create another directory to the `tutorials` folder and put the images there (new directory called `images`)

**Comment by CentreMetre** [comment]
Thanks for confirming to use 17, i did put 17 in the tutorial, and i did put images in, but then removed them since I'm not sure if its a good idea them being in the repo because it will increase the size for people downloading. I've seen something about user-images.githubusercontent.com but I'm not sure how you do that, i have the images on my machine still so I can just upload them and add them to the README.md when they're uploaded somewhere.

**Comment by xspanger3770** [comment]
Hi, putting the images to this repo will surely not increase the download size, as only the `src/` folder is used when creating the jar file. 

Update:
In fact, you can simply drag the images inside your README.md file while editing, and it will get uploaded to some GitHub storage and thus no need to save them to the folder. 

If you don't want to do MacOS, that's fine, we can leave it for future and yes, you can open issue for that. It might also be a great idea, after the tutorial is finished, to try it on fresh Linux install to see if there aren't any unexpected problems.

**Comment by CentreMetre** [comment]
I meant for people cloning the repo for development, unless theres also a way to exclude that, or people only download/clone from a certain branch that doesnt include the tutorial folder and thus the images?

Didnt know you could do that with the pictures, ill give it a try.

Also its not that i dont want to do MacOS, its that i cant since i dont own a MacOS device. So yea ill open an issue about adding MacOS to the tutorial. 

Yea didnt think about **fresh** linux install, was gonna do it on my install but there could be problems since i wouldnt be surprised if ive knackered something on my install somehow...
